Database:  localhost:C:/Program Files/Firebird/Firebird_1_5/Database/plantLore.fdb, User: SYSDBA

SET SQL DIALECT 3;

/* CREATE DATABASE 'localhost:C:/Program Files/Firebird/Firebird_1_5/Database/plantLore.fdb' DEFAULT CHARACTER SET ISO8859_1 */


CREATE GENERATOR GEN_TAUTHORS;
CREATE GENERATOR GEN_TGPS;
CREATE GENERATOR GEN_THABITATS;
CREATE GENERATOR GEN_TOCCURENCES;
CREATE GENERATOR GEN_TPHYTOCHORIA;
CREATE GENERATOR GEN_TPLANTS;


/* Table: TAUTHORS, Owner: SYSDBA */
CREATE TABLE TAUTHORS (CID INTEGER NOT NULL,
        CFIRSTNAME VARCHAR(20) NOT NULL,
        CSURNAME VARCHAR(30) NOT NULL,
        CORGANIZATION VARCHAR(50),
        CROLE VARCHAR(100),
        CADDRESS VARCHAR(255),
        CPHONENUMBER VARCHAR(30),
        CEMAIL VARCHAR(100),
        CURL VARCHAR(100),
        CNOTE VARCHAR(256),
PRIMARY KEY (CID));

/* Table: TAUTHORSOCCURENCES, Owner: SYSDBA */
CREATE TABLE TAUTHORSOCCURENCES (CAUTHORID INTEGER NOT NULL,
        COCCURENCEID INTEGER NOT NULL);

/* Table: TGPS, Owner: SYSDBA */
CREATE TABLE TGPS (CID INTEGER NOT NULL,
        CX DOUBLE PRECISION NOT NULL,
        CY DOUBLE PRECISION NOT NULL,
        CZ DOUBLE PRECISION NOT NULL,
PRIMARY KEY (CID));

/* Table: THABITATS, Owner: SYSDBA */
CREATE TABLE THABITATS (CID INTEGER NOT NULL,
        CTERRITORYID INTEGER NOT NULL,
        CPHYTOCHORIAID INTEGER NOT NULL,
        CQUADRANT VARCHAR(10),
        CZONE VARCHAR(10),
        CDESCRIPTION VARCHAR(255),
        CNEARESTVILLAGEID INTEGER NOT NULL,
        CCOUNTRY VARCHAR(30),
        CALTITUDE DECIMAL(6, 2),
        CGPSID INTEGER,
        CNOTE VARCHAR(4096),
PRIMARY KEY (CID));

/* Table: TOCCURENCES, Owner: SYSDBA */
CREATE TABLE TOCCURENCES (CID INTEGER NOT NULL,
        CHABITATID INTEGER NOT NULL,
        CPLANTID INTEGER NOT NULL,
        CYEARCOLLECTED SMALLINT,
        CMONTHCOLLECTED SMALLINT,
        CDAYCOLLECTED SMALLINT,
        CTIMECOLLECTED TIME,
        CSOURCE VARCHAR(50),
        CHERBARIUM VARCHAR(20),
        CNOTE VARCHAR(4096),
PRIMARY KEY (CID));

/* Table: TPHYTOCHORIA, Owner: SYSDBA */
CREATE TABLE TPHYTOCHORIA (CID INTEGER NOT NULL,
        CCODE VARCHAR(5) NOT NULL,
        CNAME VARCHAR(50) NOT NULL,
PRIMARY KEY (CID));

/* Table: TPLANTS, Owner: SYSDBA */
CREATE TABLE TPLANTS (CID INTEGER NOT NULL,
        CADOPTEDNAME VARCHAR(30) NOT NULL,
        CCZECHNAME VARCHAR(30),
        CPUBLISHABLENAME VARCHAR(30),
        CNOTE VARCHAR(256),
PRIMARY KEY (CID));

/* Table: TTERRITORIES, Owner: SYSDBA */
CREATE TABLE TTERRITORIES (CID INTEGER NOT NULL,
        CNAME VARCHAR(100) NOT NULL,
PRIMARY KEY (CID));

/* Table: TVILLAGES, Owner: SYSDBA */
CREATE TABLE TVILLAGES (CID INTEGER NOT NULL,
        CNAME VARCHAR(100) NOT NULL,
PRIMARY KEY (CID));

ALTER TABLE TAUTHORSOCCURENCES ADD FOREIGN KEY (CAUTHORID) REFERENCES TAUTHORS (CID);

ALTER TABLE TAUTHORSOCCURENCES ADD FOREIGN KEY (COCCURENCEID) REFERENCES TOCCURENCES (CID);

ALTER TABLE THABITATS ADD FOREIGN KEY (CTERRITORYID) REFERENCES TTERRITORIES (CID);

ALTER TABLE THABITATS ADD FOREIGN KEY (CPHYTOCHORIAID) REFERENCES TPHYTOCHORIA (CID);

ALTER TABLE THABITATS ADD FOREIGN KEY (CNEARESTVILLAGEID) REFERENCES TVILLAGES (CID);

ALTER TABLE THABITATS ADD FOREIGN KEY (CGPSID) REFERENCES TGPS (CID);

ALTER TABLE TOCCURENCES ADD FOREIGN KEY (CHABITATID) REFERENCES THABITATS (CID);

ALTER TABLE TOCCURENCES ADD FOREIGN KEY (CPLANTID) REFERENCES TPLANTS (CID);

/* Grant permissions for this database */