/*
 * AddEditUserView.java
 *
 * Created on 23. duben 2006, 15:44
 */

package net.sf.plantlore.client.user;

import java.text.DateFormat;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JDialog;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import net.sf.plantlore.l10n.L10n;

/**
 *
 * @author  Lada
 */
public class AddEditUserView extends javax.swing.JDialog  implements Observer {
    
    /**
     * Creates new form AddEditUserView
     */
    public AddEditUserView(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();        
    }
    
     public void update(Observable observable, Object object)
    {
    }
    
     /*
      * nastaveni formulare pro add
      */
     public void setAddForm() {
         operationButton.setText("Add");
         
     }
     
      public void setEditForm() {
         operationButton.setText("Edit");
         
     }
     
     public void setDetailsForm() {
       operationButton.setText("Ok");
       this.loginText.setEditable(false);
       this.passwordtext.setEditable(false);
       this.firstNameText.setEditable(false);
       this.surnameText.setEditable(false);
       this.emailText.setEditable(false);
       this.addressText.setEditable(false);
       this.createWhenText.setEditable(false);
       this.dropWhenText.setEditable(false);
       this.administratorCheckBox.setEnabled(false);
       this.editAllCheckBox.setEnabled(false);       
       this.addRightCheckBox.setEnabled(false);
       this.editGroupText.setEditable(false);
       this.seeColumnText.setEditable(false);
       this.noteText.setEditable(false);
     }
     
     /**
     *
     */
    public void close() {
        dispose();
    }
    
    /*
     *
     */
    public boolean checkNotNull() {
        //if (this.collectionNameText.getText().equals("") && this.colllectionYearPublictionText.getText().enable("") && this.journalNameText.getText().equals("") && this.journalAuthorNameText.getText().equals("")) {
        //   JOptionPane.showMessageDialog(this, ".... is a compulsory field. Please fill it in.", "Missing compulsory field", JOptionPane.ERROR_MESSAGE);
        //    return false;
        //}
        return true;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        createWhenuser = new javax.swing.JLabel();
        loginText = new javax.swing.JTextField();
        firstNameText = new javax.swing.JTextField();
        surnameText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        addressText = new javax.swing.JTextField();
        noteLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        noteText = new javax.swing.JTextArea();
        dropWhenLabel = new javax.swing.JLabel();
        passwordtext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rightUserLabel = new javax.swing.JLabel();
        administratorCheckBox = new javax.swing.JCheckBox();
        editAllCheckBox = new javax.swing.JCheckBox();
        addRightCheckBox = new javax.swing.JCheckBox();
        editGroupLabel = new javax.swing.JLabel();
        editGroupText = new javax.swing.JTextField();
        seeColumnLabel = new javax.swing.JLabel();
        seeColumnText = new javax.swing.JTextField();
        createWhenText = new JFormattedTextField(DateFormat.getDateTimeInstance(DateFormat.MEDIUM, DateFormat.SHORT,L10n.getCurrentLocale()));
        dropWhenText = new JFormattedTextField(DateFormat.getDateTimeInstance(DateFormat.MEDIUM, DateFormat.SHORT,L10n.getCurrentLocale()));
        operationButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("User"));
        loginLabel.setText(L10n.getString("user.login"));

        firstNameLabel.setText(L10n.getString("user.firstName"));

        surnameLabel.setText(L10n.getString("user.surname"));

        emailLabel.setText(L10n.getString("user.email"));

        addressLabel.setText(L10n.getString("user.address"));

        createWhenuser.setText(L10n.getString("user.createWhen"));

        noteLabel.setText(L10n.getString("user.note"));

        noteText.setColumns(20);
        noteText.setRows(5);
        jScrollPane1.setViewportView(noteText);

        dropWhenLabel.setText(L10n.getString("user.dropWhen"));

        jLabel2.setText(L10n.getString("user.password"));

        rightUserLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        rightUserLabel.setText(L10n.getString("user.right"));

        administratorCheckBox.setText(L10n.getString("right.administrator"));
        administratorCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        administratorCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        editAllCheckBox.setText(L10n.getString("right.editAll"));
        editAllCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        editAllCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        addRightCheckBox.setText(L10n.getString("right.add"));
        addRightCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        addRightCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        editGroupLabel.setText(L10n.getString("right.editGroup"));

        seeColumnLabel.setText(L10n.getString("right.seeColumn"));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(loginLabel)
                    .add(addressLabel)
                    .add(emailLabel)
                    .add(surnameLabel)
                    .add(firstNameLabel)
                    .add(jLabel2)
                    .add(createWhenuser)
                    .add(dropWhenLabel)
                    .add(noteLabel))
                .add(70, 70, 70)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jScrollPane1)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, addressText)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, emailText)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, surnameText)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, firstNameText)
                    .add(loginText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, passwordtext)
                    .add(createWhenText)
                    .add(dropWhenText))
                .add(27, 27, 27)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(administratorCheckBox)
                    .add(rightUserLabel)
                    .add(editAllCheckBox)
                    .add(editGroupLabel)
                    .add(editGroupText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .add(seeColumnLabel)
                    .add(seeColumnText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .add(addRightCheckBox))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(loginLabel)
                            .add(loginText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(rightUserLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(passwordtext, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel2)
                            .add(administratorCheckBox))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(firstNameText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(firstNameLabel)
                            .add(editAllCheckBox))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(surnameText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(surnameLabel)
                            .add(addRightCheckBox))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(emailText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(emailLabel))
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(19, 19, 19)
                                .add(editGroupLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(editGroupText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(addressText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(addressLabel))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(createWhenuser)
                                    .add(createWhenText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(188, 188, 188)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(dropWhenLabel)
                            .add(dropWhenText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(14, 14, 14)
                        .add(noteLabel))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(seeColumnLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(seeColumnText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .add(31, 31, 31))
        );

        operationButton.setText("Add");

        closeButton.setText(L10n.getString("Close"));

        helpButton.setText(L10n.getString("Help"));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(200, 200, 200)
                .add(operationButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(21, 21, 21)
                .add(closeButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(14, 14, 14)
                .add(helpButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(100, 100, 100)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(operationButton)
                    .add(closeButton)
                    .add(helpButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEditUserView(new javax.swing.JDialog(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JCheckBox addRightCheckBox;
    private javax.swing.JLabel addressLabel;
    protected javax.swing.JTextField addressText;
    protected javax.swing.JCheckBox administratorCheckBox;
    protected javax.swing.JButton closeButton;
    protected javax.swing.JFormattedTextField createWhenText;
    private javax.swing.JLabel createWhenuser;
    private javax.swing.JLabel dropWhenLabel;
    protected javax.swing.JFormattedTextField dropWhenText;
    protected javax.swing.JCheckBox editAllCheckBox;
    private javax.swing.JLabel editGroupLabel;
    protected javax.swing.JTextField editGroupText;
    private javax.swing.JLabel emailLabel;
    protected javax.swing.JTextField emailText;
    private javax.swing.JLabel firstNameLabel;
    protected javax.swing.JTextField firstNameText;
    protected javax.swing.JButton helpButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loginLabel;
    protected javax.swing.JTextField loginText;
    private javax.swing.JLabel noteLabel;
    protected javax.swing.JTextArea noteText;
    protected javax.swing.JButton operationButton;
    protected javax.swing.JTextField passwordtext;
    private javax.swing.JLabel rightUserLabel;
    private javax.swing.JLabel seeColumnLabel;
    protected javax.swing.JTextField seeColumnText;
    private javax.swing.JLabel surnameLabel;
    protected javax.swing.JTextField surnameText;
    // End of variables declaration//GEN-END:variables
    
}
