/*
 * PrintView.java
 *
 * Created on 19. květen 2006, 17:13
 */

package net.sf.plantlore.client;

import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author  fraktalek
 */
public class PrintView extends javax.swing.JDialog implements Observer {
    private Print model;
    
    /** Creates new form PrintView */
    public PrintView(java.awt.Frame parent, boolean modal, Print model) {
        super(parent, modal);
        this.model = model;
        initComponents();
        model.addObserver(this);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        numOfRecordsLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        reportField = new javax.swing.JTextField();
        chooseButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        helpButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        previewButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();

        numOfRecordsLabel.setText("Number of selected records to print:");

        jLabel1.setText("Use report:");

        chooseButton.setText("Choose");

        helpButton.setText("Help");

        cancelButton.setText("Cancel");

        previewButton.setText("Preview");

        printButton.setText("Print");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(helpButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 145, Short.MAX_VALUE)
                .add(cancelButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(previewButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(printButton)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(new java.awt.Component[] {cancelButton, helpButton, previewButton, printButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(helpButton)
                    .add(printButton)
                    .add(previewButton)
                    .add(cancelButton))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(numOfRecordsLabel)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(reportField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chooseButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(numOfRecordsLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(reportField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(chooseButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 36, Short.MAX_VALUE)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintView(new javax.swing.JFrame(), true, new Print()).setVisible(true);
            }
        });
    }

    public void update(Observable o, Object arg) {
        if (arg != null && arg instanceof String) {
            String msg = (String)arg;
            if (msg.equals("REPORT_CHOSEN")) {
                if (model.getTheChosenOne() != null) {
                    reportField.setText(model.getTheChosenOne().getAbsolutePath());
                    previewButton.setEnabled(true);
                    printButton.setEnabled(true);
                } else {
                    previewButton.setEnabled(false);
                    printButton.setEnabled(false);
                }
                return;
            }
            if (msg.equals("NEW_SOURCE")) {
                numOfRecordsLabel.setText("Number of records to print: "+model.getSelection().values().size());
                return;
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton cancelButton;
    protected javax.swing.JButton chooseButton;
    protected javax.swing.JButton helpButton;
    protected javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JLabel numOfRecordsLabel;
    protected javax.swing.JButton previewButton;
    protected javax.swing.JButton printButton;
    protected javax.swing.JTextField reportField;
    // End of variables declaration//GEN-END:variables
    
}
