/*
 * SchedaView.java
 *
 * Created on 18. květen 2006, 14:38
 */

package net.sf.plantlore.client;

import java.awt.BorderLayout;
import java.awt.Dimension;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JRViewer;

/**
 *
 * @author  fraktalek
 */
public class SchedaView extends javax.swing.JDialog {
    
    /** Creates new form SchedaView */
    public SchedaView(java.awt.Frame parent, boolean modal, JasperPrint jasperPrint) {
        super(parent, modal);
        initComponents();
        JRViewer jrv = new JRViewer(jasperPrint);
        jrv.setPreferredSize(new Dimension(670,550));
        add(jrv, BorderLayout.CENTER);        
        pack();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchedaView(new javax.swing.JFrame(), true, new JasperPrint()).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
