package net.sf.plantlore.client.login;

import java.awt.Dialog;
import java.util.Observable;
import java.util.Observer;

import net.sf.plantlore.common.DefaultEscapeKeyPressed;
import net.sf.plantlore.common.DocumentSizeFilter;
import net.sf.plantlore.common.PlantloreHelp;
import net.sf.plantlore.l10n.L10n;

/**
 * ItemView displays the dialog where the User can alter values
 * that are required for connection making. The values are pre-filled
 * according to the currently selected record.
 *
 * @author  Erik Kratochvíl
 * @see Login#getSelected()
 */
public class ItemView2 extends javax.swing.JDialog implements Observer {
    
	private Login model;
	
    public ItemView2(Dialog parent, Login model) {
    	super(parent, true);
    	
		this.model = model;
		model.addObserver(this);
		initComponents();
		getRootPane().setDefaultButton(next);
		setLocationRelativeTo(null);
		
		PlantloreHelp.addKeyHelp(PlantloreHelp.LOGIN, this.getRootPane());
        PlantloreHelp.addButtonHelp(PlantloreHelp.LOGIN, this.help);
        
        new DefaultEscapeKeyPressed( this );
		
		DocumentSizeFilter.patch(aliasLocal, 50);
		DocumentSizeFilter.patch(aliasRemote, 50);
		DocumentSizeFilter.patch(databaseEngine, 30);
		DocumentSizeFilter.patch(databaseIdentifier, 30);
		DocumentSizeFilter.patch(databaseParameter, 60);
		DocumentSizeFilter.patch(databasePort, 5);
		DocumentSizeFilter.patch(host, 50);
		DocumentSizeFilter.patch(port, 5);
		DocumentSizeFilter.patch(remoteDatabaseIdentifier, 30);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        aliasLocal = new javax.swing.JTextField();
        databaseIdentifier = new javax.swing.JTextField();
        databasePort = new javax.swing.JTextField();
        databaseParameter = new javax.swing.JTextField();
        databaseEngine = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        aliasRemote = new javax.swing.JTextField();
        host = new javax.swing.JTextField();
        port = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        remoteDatabaseIdentifier = new javax.swing.JTextField();
        next = new javax.swing.JButton();
        discard = new javax.swing.JButton();
        help = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel1.setText(L10n.getString("Login.Alias"));

        jLabel2.setText(L10n.getString("Login.DatabaseEngine"));

        jLabel3.setText(L10n.getString("Login.DatabaseIdentifier"));

        jLabel4.setText(L10n.getString("Login.DatabasePort"));

        jLabel5.setText(L10n.getString("Login.DatabaseParameter"));

        aliasLocal.setToolTipText(L10n.getString("Login.AliasTT"));

        databaseIdentifier.setToolTipText(L10n.getString("Login.DatabaseIdentifierTT"));

        databasePort.setToolTipText(L10n.getString("Login.DatabasePortTT"));

        databaseParameter.setToolTipText(L10n.getString("Login.DatabaseParameterTT"));

        databaseEngine.setEditable(true);
        databaseEngine.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "postgresql", "firebirdsql", "mysql", "oraclesql" }));
        databaseEngine.setToolTipText(L10n.getString("Login.DatabaseEngineTT"));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jLabel3)
                    .add(jLabel4)
                    .add(jLabel5)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(databaseParameter, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .add(databasePort, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .add(databaseIdentifier, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .add(databaseEngine, 0, 301, Short.MAX_VALUE)
                    .add(aliasLocal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(aliasLocal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(databaseEngine, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(databaseIdentifier, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(databasePort, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(databaseParameter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jTabbedPane1.addTab(L10n.getString("Login.LocalDatabase"), jPanel1);

        jLabel8.setText(L10n.getString("Login.Alias"));

        jLabel9.setText(L10n.getString("Login.HostName"));

        jLabel10.setText(L10n.getString("Login.Port"));

        aliasRemote.setToolTipText(L10n.getString("Login.AliasTT"));

        host.setToolTipText(L10n.getString("Login.HostNameTT"));

        port.setToolTipText(L10n.getString("Login.PortTT"));

        jLabel11.setText(L10n.getString("Login.DatabaseIdentifier"));

        remoteDatabaseIdentifier.setToolTipText(L10n.getString("Login.DatabaseIdentifierTT"));

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel8)
                    .add(jLabel9)
                    .add(jLabel10)
                    .add(jLabel11))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(port, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, aliasRemote, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(host, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                    .add(remoteDatabaseIdentifier, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(aliasRemote, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(host, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(port, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(remoteDatabaseIdentifier, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jTabbedPane1.addTab(L10n.getString("Login.RemoteDatabase"), jPanel2);

        next.setText(L10n.getString("Login.Change"));

        discard.setText(L10n.getString("Common.Cancel"));

        help.setText(L10n.getString("Common.Help"));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(help)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 171, Short.MAX_VALUE)
                        .add(discard)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(next)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {discard, next}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(next)
                    .add(discard)
                    .add(help))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    /**
     * Fill all fields of the dialog
     * with information obtained from the currently selected record.
     */
    public void update(Observable arg0, Object arg1) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				DBInfo info = model.getSelected();
				
				if(info != null) {
					if(info.host == null || info.host.length() == 0) {
						jTabbedPane1.setSelectedIndex(0);
						
						// Direct connection (without any contact with a server)
						aliasLocal.setText(info.alias);
						((javax.swing.JTextField)databaseEngine.getEditor().getEditorComponent()).setText(info.databaseType);
						databaseIdentifier.setText(info.getDatabaseIdentifier());
						if(info.databasePort > 0)
							databasePort.setText( Integer.toString(info.getDatabasePort()) );
						databaseParameter.setText(info.getDatabaseParameter());
						
						// Neutralize other fields
						aliasRemote.setText("");
						host.setText("");
						port.setText("");
						remoteDatabaseIdentifier.setText("");
					}
					else {
						jTabbedPane1.setSelectedIndex(1);
						
						// Remote connection (via the Plantlore Server)
						aliasRemote.setText(info.alias);
						host.setText(info.host);
						if(info.port > 0) 
							port.setText( Integer.toString(info.port) );
						remoteDatabaseIdentifier.setText(info.databaseIdentifier);
						
						// Neutralize other fields
						aliasLocal.setText("");
						((javax.swing.JTextField)databaseEngine.getEditor().getEditorComponent()).setText("");
						databaseIdentifier.setText("");
						databasePort.setText("");
						databaseParameter.setText("");
					}
				}
			}
		});
	}
    
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextField aliasLocal;
    protected javax.swing.JTextField aliasRemote;
    protected javax.swing.JComboBox databaseEngine;
    protected javax.swing.JTextField databaseIdentifier;
    protected javax.swing.JTextField databaseParameter;
    protected javax.swing.JTextField databasePort;
    protected javax.swing.JButton discard;
    protected javax.swing.JButton help;
    protected javax.swing.JTextField host;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    protected javax.swing.JTabbedPane jTabbedPane1;
    protected javax.swing.JButton next;
    protected javax.swing.JTextField port;
    protected javax.swing.JTextField remoteDatabaseIdentifier;
    // End of variables declaration//GEN-END:variables
    
}
