/*
 * SimpleProgressBar2.java
 *
 * Created on 4. září 2006, 19:37
 */

package net.sf.plantlore.common;

import java.awt.Cursor;
import java.util.Observable;
import java.util.Observer;

import javax.swing.SwingUtilities;

import net.sf.plantlore.l10n.L10n;

/**
 *
 * @author  yaa
 */
public class SimpleProgressBar2 extends javax.swing.JDialog implements Observer {
	
	private Task monitoredTask;
    
    /** Creates new form SimpleProgressBar2 */
    public SimpleProgressBar2(Task task, java.awt.Frame parent) {
    	super(parent, true);
    	monitoredTask = task;
    	task.addObserver( this );
    	
        initComponents();
        
        setLocationRelativeTo(null);
        
        cancel.setAction( new StandardAction("Common.Cancel") {
        	public void actionPerformed(java.awt.event.ActionEvent arg0) {
        		monitoredTask.kill();
        		monitoredTask.deleteObservers();
        		Dispatcher.getDispatcher().finished();
        		
        		 SwingUtilities.invokeLater(new Runnable() {
                     public void run() {
                         setVisible( false );
                     }
                 });
        	}
        });
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        status = new javax.swing.JTextArea();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(L10n.getString("Common.Progress"));

        status.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        status.setColumns(20);
        status.setEditable(false);
        status.setRows(2);
        status.setTabSize(2);
        status.setAutoscrolls(false);
        status.setBorder(null);
        status.setEnabled(false);
        status.setFocusable(false);
        jScrollPane1.setViewportView(status);

        cancel.setText(L10n.getString("Common.Cancel"));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .add(jProgressBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, cancel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jProgressBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cancel)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton cancel;
    protected javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTextArea status;
    // End of variables declaration//GEN-END:variables
    
    
    @Override
    public void setVisible(boolean visible) {
    	super.setVisible(visible);
    	if( visible )
    		Dispatcher.getDispatcher().justDispatch( monitoredTask );

    }
    
    
	public void update(Observable arg0, Object parameter) {
		System.out.println(parameter);
		// TODO Auto-generated method stub
		if(parameter instanceof Pair) {
    		Pair p = (Pair)parameter;
            Object first = p.getFirst();
            if (first instanceof Task.Message) {
            	Task.Message msg = (Task.Message)first;
                Object value = p.getSecond();
                
                switch (msg) {
                case STARTING:
                	SwingUtilities.invokeLater(new Runnable() {
                        public void run() {
                        	  setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                              cancel.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                        }
                    });
                
                case POSITION_CHANGED:
                    SwingUtilities.invokeLater(new Runnable() {
                        public void run() {
                        	jProgressBar1.setValue(monitoredTask.getPosition());
                        }
                    });
                    break;
                case MESSAGE_CHANGED:
                    SwingUtilities.invokeLater(new Runnable() {
                        public void run() {
                            status.setText( monitoredTask.getStatusMessage() );
                        }
                    });
                    break;
                case STOPPING:
                case STOPPED:
                	SwingUtilities.invokeLater(new Runnable() {
                        public void run() {
                        	setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                        	cancel.setText(L10n.getString("Common.Hide"));
                        }
                    });
                
                }
            }
    	}
    	else if (parameter instanceof Exception) {
            DefaultExceptionHandler.handle(this, (Exception)parameter);
        }
		
	}
    
}
