/*
 * ConnectionMonitor.java
 */

package net.sf.plantlore.common.debug;

import java.rmi.RemoteException;
import net.sf.plantlore.client.AppCore;

/**
 *
 * @author  Tomas Kovarik
 */
public class ConnectionMonitor extends javax.swing.JFrame {
    AppCore model;
    /** Creates new form ConnectionMonitor */
    public ConnectionMonitor(AppCore _model) {
        this.model = _model;
        initComponents();
        this.setLocation(400,0);
                
        progress.setMaximum(100); // Default maximum number of connections on PostgreSQL
        progress.setStringPainted(true);

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        }
        );
        
    
        Thread t = new Thread() {
        	private Thread update = new Thread() {
            	public void run() {
                        int total = 0;
                        if (model.getDatabase() != null) {
                            try {
                                total = model.getDatabase().getConnectionCount();
                            } catch (Exception e) {
                                // Don't care
                            }
                        }
                	progress.setValue(total);
                	progress.setString(total + " connections");
            	}
            };
            
        	public void run() {
                while(true) {
                	java.awt.EventQueue.invokeLater( update );
                	try {
                		Thread.sleep(1000);
                	} catch(Exception e) {
                		// Who cares
                	}
                }
            }
        };
        
        t.setDaemon(true);
        t.start();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        progress = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Database connections");
        setAlwaysOnTop(true);
        setName("connectionMonitorFrame");
        setResizable(false);
        setUndecorated(true);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(progress, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(progress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar progress;
    // End of variables declaration//GEN-END:variables
    
}
