/*
 * MemoryMonitor.java
 *
 * Created on 1. srpen 2006, 11:18
 */

package net.sf.plantlore.common.debug;

/**
 *
 * @author  yaa
 */
public class MemoryMonitor extends javax.swing.JFrame {
    
    /** Creates new form MemoryMonitor */
    public MemoryMonitor() {
        initComponents();
        
        progress.setMaximum(512); // My computer has 512MB memory [java -Xmx512m]
        progress.setStringPainted(true);

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        }
        );
        
    
        Thread t = new Thread() {
        	private Thread update = new Thread() {
            	public void run() {
            		float total = Runtime.getRuntime().totalMemory() / (1024.0f*1024.0f);
                	progress.setValue( (int)total );
                	progress.setString(Float.toString( Math.round(total*10) / 10.0f ) + "MB");
            	}
            };
            
        	public void run() {
                while(true) {
                	java.awt.EventQueue.invokeLater( update );
                	try {
                		Thread.sleep(1000);
                	} catch(Exception e) {
                		// Who cares
                	}
                }
            }
        };
        
        t.setDaemon(true);
        t.start();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        progress = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Memory consumption");
        setAlwaysOnTop(true);
        setName("memoryMonitorFrame");
        setResizable(false);
        setUndecorated(true);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(progress, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(progress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar progress;
    // End of variables declaration//GEN-END:variables
    
}
