/*
 * CreateDBAuthView.java
 *
 * Created on 29. srpen 2006, 15:49
 */

package net.sf.plantlore.client.createdb;

import java.awt.Dialog;
import java.util.Observable;
import java.util.Observer;

import net.sf.plantlore.client.login.DBInfo;
import net.sf.plantlore.common.AutoComboBox;
import net.sf.plantlore.l10n.L10n;

/**
 *
 * @author  yaa
 */
public class CreateDBAuthView extends javax.swing.JDialog implements Observer {
	
    
    /** Creates new form CreateDBAuthView */
    public CreateDBAuthView(Dialog parent, CreateDB model) {
    	super(parent, true);
    	
    	model.addObserver(this);
        initComponents();
        
        setLocationRelativeTo(null); // center of the screen
        getRootPane().setDefaultButton(create);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        user = new AutoComboBox();
        ((AutoComboBox)user).setStrict(false);
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        create = new javax.swing.JButton();

        jLabel1.setText(L10n.getString("Login.UserName"));

        user.setEditable(true);

        jLabel2.setText(L10n.getString("Login.Password"));

        create.setText(L10n.getString("CreateDB.Create"));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(user, 0, 223, Short.MAX_VALUE)
                            .add(password, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, create))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(user, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(password, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(create)
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {password, user}, org.jdesktop.layout.GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    protected javax.swing.JPasswordField password;
    protected javax.swing.JComboBox user;
    // End of variables declaration//GEN-END:variables
    
    
 
    
	public void update(Observable source, final Object parameter) {
		java.awt.EventQueue.invokeLater(new Runnable() {
    		public void run() {
    			if(parameter instanceof DBInfo) {
    				setVisible(false);
    				password.setText("");
    			}
    		}
		});
	}
    
}
