package net.sf.plantlore.client.createdb;

import java.awt.Dialog;
import java.util.Observable;
import java.util.Observer;

import net.sf.plantlore.client.login.DBInfo;
import net.sf.plantlore.common.DefaultEscapeKeyPressed;
import net.sf.plantlore.common.DocumentSizeFilter;
import net.sf.plantlore.l10n.L10n;

/**
 * The view allows the User to specify the Authentication information
 * - the User name (or the Account name) and the Password of that account.
 * 
 * @author kaimu
 */
public class CreateDBAuthView extends javax.swing.JDialog implements Observer {
    
    
    public CreateDBAuthView(Dialog parent, CreateDB model) {
    	super(parent, true);
    	
    	model.addObserver(this);
        initComponents();
        
        setLocationRelativeTo(null); // center of the screen
        getRootPane().setDefaultButton(create);
        /*
        PlantloreHelp.addKeyHelp(PlantloreHelp.CREATE_DB, this.getRootPane());
        PlantloreHelp.addButtonHelp(PlantloreHelp.CREATE_DB, this.help);
        */
        new DefaultEscapeKeyPressed( this );

        DocumentSizeFilter.patch(password, 20);
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        create = new javax.swing.JButton();
        user = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();

        setTitle(L10n.getString("Login.Authentication"));
        jLabel1.setText(L10n.getString("Login.UserName"));

        jLabel2.setText(L10n.getString("Login.Password"));

        password.setToolTipText(L10n.getString("Login.PasswordTT"));

        create.setText(L10n.getString("CreateDB.Create"));

        user.setToolTipText(L10n.getString("Login.UserNameTT"));

        cancel.setText(L10n.getString("Common.Cancel"));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(user, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                            .add(password, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(create)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cancel)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {cancel, create}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(user, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(password, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancel)
                    .add(create))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {password, user}, org.jdesktop.layout.GroupLayout.VERTICAL);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton cancel;
    protected javax.swing.JButton create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    protected javax.swing.JPasswordField password;
    protected javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
    
    
    public void update(Observable source, final Object parameter) {
		java.awt.EventQueue.invokeLater(new Runnable() {
    		public void run() {
    			if(parameter instanceof DBInfo)
    				setVisible(false);
    		}
		});
	}

    
}
