/*
 * ServerCreateView.java
 *
 * Created on 1. červen 2006, 19:21
 */

package net.sf.plantlore.server.manager;

import java.util.Observable;
import java.util.Observer;

import javax.swing.JOptionPane;

import net.sf.plantlore.l10n.L10n;
import net.sf.plantlore.server.ServerSettings;

/**
 *
 * @author  yaa
 */
public class ServerCreateView extends javax.swing.JFrame implements Observer {
    
	
//	private ServerMng model;

	
    /** Creates new form ServerCreateView */
    public ServerCreateView(ServerMng model) {
    	model.addObserver(this);
        initComponents();
        getRootPane().setDefaultButton(next);
        setLocationRelativeTo(null); // center of the screen
        
        // Initialize the components' contents.
        ServerSettings settings = model.getSettings(true);
        if(settings != null) {
        	// Server
        	serverPort.setText( new Integer(settings.getPort()).toString() );
        	// Database
        	databasePort.setText( new Integer(settings.getDatabaseSettings().getPort()).toString() );
        	( (javax.swing.JTextField)databaseType.getEditor().getEditorComponent() )
        	.setText( settings.getDatabaseSettings().getDatabase() );
        	databaseUser.setText( settings.getDatabaseSettings().getMasterUser() );
        	databasePassword.setText( settings.getDatabaseSettings().getMasterPassword() );
        	databaseParameter.setText( settings.getDatabaseSettings().getConnectionStringSuffix() );
        }
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        plantloreLogo = new javax.swing.JPanel();
        next = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        serverPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        serverPort = new javax.swing.JTextField();
        status = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        databaseType = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        databasePort = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        databaseUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        databasePassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        databaseParameter = new javax.swing.JTextField();
        help = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(L10n.getString("Server.Create"));
        setResizable(false);
        plantloreLogo.setBackground(new java.awt.Color(0, 0, 0));
        plantloreLogo.setPreferredSize(new java.awt.Dimension(300, 100));
        org.jdesktop.layout.GroupLayout plantloreLogoLayout = new org.jdesktop.layout.GroupLayout(plantloreLogo);
        plantloreLogo.setLayout(plantloreLogoLayout);
        plantloreLogoLayout.setHorizontalGroup(
            plantloreLogoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 433, Short.MAX_VALUE)
        );
        plantloreLogoLayout.setVerticalGroup(
            plantloreLogoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        next.setText(L10n.getString("Server.Create"));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, L10n.getString("Server.ServerSettings")));
        jLabel2.setText(L10n.getString("Server.Password"));

        serverPassword.setToolTipText(L10n.getString("Server.PasswordTT"));

        jLabel1.setText(L10n.getString("Server.Port"));

        serverPort.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        serverPort.setText("1099");
        serverPort.setToolTipText(L10n.getString("Server.PortTT"));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(serverPassword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(serverPort, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(serverPort, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1)
                    .add(serverPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        status.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, L10n.getString("Server.DatabaseSettings")));
        jLabel5.setText(L10n.getString("Server.DatabaseType"));

        databaseType.setEditable(true);
        databaseType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "postgresql", "firebirdsql", "mysql", "oraclesql" }));
        databaseType.setToolTipText(L10n.getString("Server.DatabaseTypeTT"));

        jLabel6.setText(L10n.getString("Server.DatabasePort"));

        databasePort.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        databasePort.setText("5432");
        databasePort.setToolTipText(L10n.getString("Server.DatabasePortTT"));

        jLabel3.setText(L10n.getString("Server.DatabaseUser"));

        databaseUser.setToolTipText(L10n.getString("Server.DatabaseUserTT"));

        jLabel4.setText(L10n.getString("Server.DatabasePassword"));

        databasePassword.setToolTipText(L10n.getString("Server.DatabasePasswordTT"));

        jLabel7.setText(L10n.getString("Server.DatabaseParameter"));

        databaseParameter.setToolTipText(L10n.getString("Server.DatabaseParameterTT"));

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel5)
                    .add(jLabel3)
                    .add(jLabel7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(databaseType, 0, 264, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(databasePort, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(databaseParameter, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(databaseUser, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(databasePassword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(databasePort, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6)
                    .add(databaseType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(databaseUser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4)
                    .add(databasePassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(databaseParameter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        help.setText(L10n.getString("Common.Help"));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(help)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 307, Short.MAX_VALUE)
                .add(next)
                .addContainerGap())
            .add(status, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, plantloreLogo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(plantloreLogo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(next)
                    .add(help))
                .add(11, 11, 11)
                .add(status, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextField databaseParameter;
    protected javax.swing.JPasswordField databasePassword;
    protected javax.swing.JTextField databasePort;
    protected javax.swing.JComboBox databaseType;
    protected javax.swing.JTextField databaseUser;
    protected javax.swing.JButton help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    protected javax.swing.JButton next;
    protected javax.swing.JPanel plantloreLogo;
    protected javax.swing.JPasswordField serverPassword;
    protected javax.swing.JTextField serverPort;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables

    
	public void update(Observable source, final Object parameter) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				if(parameter instanceof String)
					status.setText( " " + (String)parameter );
				else if(parameter instanceof Exception) {
					JOptionPane.showMessageDialog(null,
							((Exception)parameter).getMessage(),
						    L10n.getString("Error.ServerLoginFailed"),
						    JOptionPane.ERROR_MESSAGE);
				}
			}
		});
	}
	
    
}
