package net.sf.plantlore.server.manager;

import net.sf.plantlore.l10n.L10n;


/**
 * The server connection/creation dialog.
 *
 * @author  Erik Kratochvíl (discontinuum@gmail.com)
 */
public class ServerLoginView extends javax.swing.JFrame {
	
	ServerMng model;
    
    /** Creates new form ServerLoginView */
    public ServerLoginView(ServerMng model) {
    	this.model = model;
        initComponents();
        setLocationRelativeTo(null); // center of the screen
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        host = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        next = new javax.swing.JButton();
        imageHere = new javax.swing.JPanel();
        createNew = new javax.swing.JRadioButton();
        connectExisting = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel1.setText(L10n.getString("HostPort"));

        jLabel2.setText(L10n.getString("Password"));

        host.setText("localhost:1099");

        next.setText("Next");

        imageHere.setBackground(new java.awt.Color(0, 0, 0));
        org.jdesktop.layout.GroupLayout imageHereLayout = new org.jdesktop.layout.GroupLayout(imageHere);
        imageHere.setLayout(imageHereLayout);
        imageHereLayout.setHorizontalGroup(
            imageHereLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 397, Short.MAX_VALUE)
        );
        imageHereLayout.setVerticalGroup(
            imageHereLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 198, Short.MAX_VALUE)
        );

        buttonGroup1.add(createNew);
        createNew.setSelected(true);
        createNew.setText("Create and start a new server");
        createNew.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        createNew.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup1.add(connectExisting);
        connectExisting.setText("Connect to a running server");
        connectExisting.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        connectExisting.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(imageHere, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(createNew)
                    .add(connectExisting)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(host, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                            .add(password, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, next))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(imageHere, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(createNew)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(connectExisting)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(host, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(password, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(next)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    protected javax.swing.JRadioButton connectExisting;
    protected javax.swing.JRadioButton createNew;
    protected javax.swing.JTextField host;
    protected javax.swing.JPanel imageHere;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    protected javax.swing.JButton next;
    protected javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
    
}
